Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,8 +1,3 @@
-# trigger: 
-#   branches:
-#     include:
-#       - main
-
 pr:
   branches:
     include:
@@ -26,6 +21,29 @@ variables:
   - group: TerraformSecrets  # Reference stored secrets in ADO
 
 stages:
+  - stage: Terraform
+    jobs:
+      - job: RunTerraform
+        steps:
+          - checkout: self
+
+          - script: ls -la $(Build.SourcesDirectory)
+            displayName: "Debug: List Available Folders"
+
+          - script: |
+              if [ -d "$(Build.SourcesDirectory)/${{ parameters.folderName }}" ]; then
+                echo "Folder exists!"
+              else
+                echo "Error: Folder does not exist!"
+                exit 1
+              fi
+            displayName: "Verify Folder Exists"
+
+          - script: |
+              cd $(Build.SourcesDirectory)/${{ parameters.folderName }} || exit 1
+              ls -la
+            displayName: "Navigate to Selected Folder"
+
   - stage: Terraform_Deployment
     displayName: "Terraform Deployment"
     jobs:
