Update azure-pipelines.yml for Azure Pipelines

diff --git a/.azure-pipelines/azure-pipelines.yml b/.azure-pipelines/azure-pipelines.yml
--- a/.azure-pipelines/azure-pipelines.yml
+++ b/.azure-pipelines/azure-pipelines.yml
@@ -40,10 +40,6 @@ stages:
                 echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN;]$ARM_OIDC_TOKEN"
                 echo "##vso[task.setvariable variable=ARM_USE_OIDC;]true"
                 echo "OIDC Token fetched successfully!"
-                export ARM_TENANT_ID="$(TENANT_ID)"
-                export ARM_SUBSCRIPTION_ID="$(SUBSCRIPTION_ID)"
-                export ARM_CLIENT_ID="$(SERVICE_PRINCIPAL_ID)"
-                export ARM_OIDC_TOKEN="$(ID_TOKEN)"
               
           # Terraform Init
            - script: |
@@ -74,9 +70,17 @@ stages:
            # Terraform Apply (only on main branch and if plan file exists)
            - task: AzureCLI@2
              displayName: "Terraform Apply"
-             inputs:
-               azureSubscription: "Terraform Deployment Connection"
-               scriptType: "bash"
-               scriptLocation: "inlineScript"
-               inlineScript: |
-                 terraform apply -auto-approve tfplan 
+           - script: |
+              #if [ -f "tfplan" ]; then
+                 terraform apply -auto-approve tfplan
+              #  else
+              #    echo "Terraform plan file not found. Skipping apply."
+              #    exit 1
+              #  fi
+             
+            #  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
+            #  env:
+            #    ARM_USE_OIDC: true
+            #    ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
+            #    ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
+            #    ARM_TENANT_ID: "$(ARM_TENANT_ID)"
